# Generated by Django 6.0 on 2025-12-31 17:42

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0003_remove_profiling_id_alter_profiling_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default=billing.models.random_ids, editable=False, max_length=23, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=12)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.profiling')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.CharField(default=billing.models.random_ids, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=230)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('itemOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payId', models.CharField(default=billing.models.random_ids, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=23)),
                ('reference_number', models.IntegerField()),
                ('payment_status', models.CharField(max_length=14)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.order')),
            ],
        ),
    ]
