# Generated by Django 5.2.4 on 2025-12-22 17:19

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=billing.models.random_ids, editable=False, max_length=23, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order_item_id',
            field=models.CharField(default=billing.models.random_ids, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
