# Generated by Django 5.2.4 on 2025-12-24 18:20

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_order_order_id_alter_orderitems_order_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payId', models.CharField(default=billing.models.random_ids, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=23)),
                ('reference_number', models.IntegerField()),
                ('payment_status', models.CharField(max_length=14)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.order')),
            ],
        ),
    ]
