# Generated by Django 5.2.4 on 2025-12-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bill_id',
            new_name='bill',
        ),
    ]
