# Generated by Django 6.0 on 2026-01-08 06:38

import Reports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('reportType', models.CharField(default=Reports.models.random_ids, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default=Reports.models.random_ids, max_length=22, primary_key=True, serialize=False)),
                ('generated_by', models.CharField(max_length=233)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Reports.reporttype')),
            ],
        ),
    ]
