# Generated by Django 6.0 on 2026-01-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='reports_pdf/'),
        ),
    ]
