# Generated by Django 4.2.11 on 2025-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('content', models.TextField()),
            ],
        ),
    ]
