# Generated by Django 5.2.4 on 2025-12-21 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiling',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=23)),
                ('password', models.CharField(max_length=23)),
                ('email', models.CharField(max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
